# 通知渠道选择,分别代表 Telegram、Bark、Anpush、钉钉
PUSH_METHOD: "DD"
# 参数：TG / ANPUSH / BARK / DD
# 例如：
# PUSH_METHOD: "TG"

# Telegram 相关
CHANNEL_ID: ""
TELEGRAM_BOT_TOKEN: ""

# Bark 相关
BARK_URL: ""
BARK_EXTRA: ""

# Anpush 相关
ANPUSH_TOKEN: ""
ANPUSH_CHANNEL: ""

# 钉钉 token
# 在群内添加机器人，获取机器人的 webhook 地址中的 token 值和签名，并将其填入 DD_BOT_TOKEN 和 DD_BOT_SECRET 中
DD_BOT_TOKEN: "YOUR_DD_BOT_TOKEN"
DD_BOT_SECRET: "YOUR_DD_BOT_SECRET"

# 是否是 Github Action
GITHUB: false

# 账号授权相关，USERNAME 和 PASSWORD 请填入你的学号和密码
USERNAME: "YOUR_STUDENT_ID"
PASSWORD: "YOUR_PASSWORD"

# 选座模式 ['1', '2', '3']
# 1 到 3 选座逐渐严格: 1 选择靠近插座且指定范围内的位置, 2 选择靠近插座的位置, 3 随机选择
MODE: '4'

# 选座范围, MODE=1 时才生效
# 这里只需要填首位号，函数会在这个范围内生成随机座位号
SEAT_ID:
  - [7480,7519]
  - [7544,7567]
  - [7784,7807]

CLASSROOMS_NAME:
  - 东校区图书馆-三层自习室

# 预约时间 ['today', 'tomorrow']
DATE: "tomorrow"